import Head from 'next/head'
import {MenuBar} from './components/MenuBar'
import {Paper} from "@mui/material";
import Box from "@mui/material/Box";
import Container from "@mui/material/Container";

export default function Home() {
  return (
    <>
      <Head>
        <title>Anwar Tax Haven</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{
          display: "flex",
          flexWrap: "wrap",
          justifyContent: "center"
      }} >
          <MenuBar></MenuBar>
          <Container sx={{
              display: "flex",
              flexWrap: "nowrap",
              flexDirection: "column-reverse",
          }} maxWidth="xl">
              <Box
                  sx={{
                      display: 'flex',
                      flexWrap: 'wrap',
                      padding: "20px",


                  }}
              >
                  <Paper sx={{
                      background: "linear-gradient(180deg, rgba(40,40,40,1) 0%, rgba(8,147,237,1) 50%, rgba(0,0,0,1) 100%);;",
                      color: "white",
                      width: "100%",
                      paddingY: "auto",
                      fontSize : "20px",
                      fontWeight: 700,
                      borderRadius: "0px",
                      height:"90vh",
                      display: "flex",
                      justifyContent: "center",
                      flexDirection: "row-reverse",
                      alignItems: "center",


                  }} elevation={0} >
                      <div style={{
                          display: "flex",
                          justifyContent: "center",

                      }} >
                          <p style={{
                              inlineSize: "150px",
                              overflowWrap: "break-word",
                              fontFamily: "'Brush Script MT', cursive",
                              border: "solid",
                              borderColor: "yellow",
                              borderRadius: "2px",
                              padding: "50px",
                              width: "100%"
                          }}>
                              Anwar Haq tax avoidance Haven
                              For all your tax avoidance needs
                              and guidelines
                          </p>

                      </div>
                  </Paper>
              </Box>
          </Container>
      </main>
    </>
  )
}
